# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Build documentation with MkDocs (optional, comment out if using Sphinx)
# mkdocs:
#   configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Python version and requirements
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  
# Install Python dependencies required to build your docs
python:
  install:
    - requirements: docs/requirements.txt